# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4adf90c7300aaca2c4f80484adb4d11fcb7042b5ecad287f6571fbe871884b23d0c707be080632d06bbfa7d6f72d44ea3c8854fa8d2e210c65ca4eccc7e75c3e

test:
  secret_key_base: 69115ff9a63ee97087b74a4c89adc36e0480ebc7ade42681ec840c0d90b68500e9587fcea324b4a50451faac7d54bbf92605bf73cc853a00ac3a0259a22b4b27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
